hydra_logging:
  formatters:
    simple:
      datefmt: "%H:%M:%S"

job_logging:
  formatters:
    simple:
      format: "[%(asctime)s][%(name)s][%(levelname)s] %(message)s"
      datefmt: "%H:%M:%S"

run:
 dir: ${output_base_dir}/hydra-outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

sweep:
  dir: ${output_base_dir}/hydra-outputs/${hydra.job.name}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}